### ISSUE TITLE
Incompatibility with the scrlayer-scrpage package

### ISSUE THREAD

**Issue by momeni** [vafa/xepersian#4]
In TeXLive 2016, using the xelatex version _3.14159265-2.6-0.99996_, the scrbook version _2016/06/14 v3.21_ document class, the **scrpage2** and the **scrlayer-scrpage** packages version _2016/06/14 v3.21_, the bidi package version _2016/09/14, v20.0_, and the xepersian package version _v16.7, 2016/09/14_, following problem happens:

Previously, the **scrpage2** package was the recommended way for customizing headers/footers when using the **scrbook** document class. Now, it has been replaced by the **scrlayer-scrpage** package. The documentation of the KOMA-Script says that its interface is not changed, but the new package causes all headers/footers to be shifted rightward and out of the page.
The problem (i.e. shifting headers out of the page) only happens when scrbook, scrlayer-scrpage, and xepersian are used together.

Minimal example:
```tex
\documentclass[fontsize=12pt,paper=A4,chapterprefix=true]{scrbook}
%\usepackage{scrpage2} % working % see headers of pages 2 and 3
\usepackage{scrlayer-scrpage} % non-working % headers are shifted out of the page

\newpagestyle{samplepagestyle}
{% header definition
	(0pt,0pt)
	{\leftmark\hfill}% even pages
	{\hfill\rightmark}% odd pages
	{\leftmark\hfill\rightmark}% one-sided layout pages
	(\textwidth,0.45pt)
}{% footer definition
	{\hfill\pagemark\hfill}% even pages
	{\hfill\pagemark\hfill}% odd pages
	{\hfill\pagemark\hfill}% one-sided layout pages
	(0pt,0pt)
}
\usepackage{xepersian}
\settextfont{XB Niloofar}

\title{عنوان نمونه}
\usepackage{lipsum}

\begin{document}
\pagestyle{samplepagestyle}\mainmatter
\renewcommand{\chaptermark}[1]{\markboth{\chaptername~\thechapter:~#1}{}}
\renewcommand{\sectionmark}[1]{\markright{بخش~\thesection:~#1}}
\chapter{مقدمه}
\section{ساختار متن}
بخش اول

\lipsum[1-12]
\end{document}
```
The issue is visible in the header of the 3rd page.

**Comment by vafa** [comment]
This is a bug of `scrlayer-scrpage` since it is not bidi-aware; please report it to koma-script authors. `bidi` along with `xepersian` already modifies over 100 packages and classes and keeping up with all these packages and classes takes too much time which unfortunately I do not have.

I am happy to fix the bugs of any packages/classes that `bidi` or `xepersian` modifies but not any other new package because it is the responsibility of the package/class authors to make their work bidi-aware not mine.

Having said that, this issue arises from the modification that `bidi` makes to the macro `\bm@l`; `\bm@l` is used in a number of higher level macros such as `\makebox` and `\framebox`. The author of koma-script needs to check for RTL mode and make definitions accordingly.
